# Generated by Django 5.1.4 on 2025-01-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogistica', '0002_semi_ano_tractor_ano_alter_chofer_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='semi',
            name='tipo',
            field=models.CharField(default='', max_length=20),
        ),
    ]
